### ISSUE TITLE
Parameters used to learn Pong?

### ISSUE THREAD

**Issue by mhauskn** [muupan/dqn-in-the-caffe#1]
What parameters were used to learn the pong player showed in the video (https://www.youtube.com/watch?v=p88R2_3yWPA)? Specifically what is the gamma/memory size/iterations needed to train dqn? I attempted to retrain the agent using the default parameters but it shows no progress after 2-million iterations. 

Thanks in advance, and very cool repo!

**Comment by muupan** [comment]
Thanks for forking my repo! Default parameters in dqn_solver.prototxt was outdated, so I've just updated it and now it's the one used in the Pong demo. The size of replay memory was 500,000.

**Comment by mhauskn** [comment]
Thanks, it seems to be working much better now :)
