### ISSUE TITLE
cannot find #include "caffe/proto/caffe.pb.h"

### ISSUE THREAD

**Issue by ghost** [muupan/dqn-in-the-caffe#2]
Hi, I really like your code! I'm trying to compile it and I get the following error,

`ajay@ajay-h8-1170uk:~/CppProjects/dqn_caffe/build$ make
Scanning dependencies of target dqn
[ 50%] Building CXX object CMakeFiles/dqn.dir/dqn_main.cpp.o
In file included from /usr/local/caffe/include/caffe/caffe.hpp:7:0,
                 from /home/ajay/CppProjects/dqn_caffe/dqn.hpp:10,
                 from /home/ajay/CppProjects/dqn_caffe/dqn_main.cpp:7:
/usr/local/caffe/include/caffe/blob.hpp:5:34: fatal error: caffe/proto/caffe.pb.h: No such file or directory
 #include "caffe/proto/caffe.pb.h"
                                  ^
compilation terminated.
make[2]: *** [CMakeFiles/dqn.dir/dqn_main.cpp.o] Error 1
make[1]: *** [CMakeFiles/dqn.dir/all] Error 2
make: *** [all] Error 2
`
My build of caffe works, but maybe there's a legacy problem?

**Comment by AjayTalati** [comment]
Very sorry, this was a fresh install of caffe, forgot to run

'make distribute'

Great project, really well written. Thank you very much for sharing it :+1:
