### ISSUE TITLE
Running Problem

### ISSUE THREAD

**Issue by mohammad63** [muupan/dqn-in-the-caffe#7]
Hello
Thanks for your code.
I have tried to compile and run the code.
Compile was OK but it gives me the following error at runtime.
It seems that the problem is related to ALE interface, but my ALE works fine separately.
I am using recommended versions of ALE and caffe
Thanks

A.L.E: Arcade Learning Environment (version 0.4)
[Powered by Stella]
Use -help for help screen.
**\* glibc detected **\* ./dqn: corrupted double-linked list: 0x00000000019b95f0 ***
======= Backtrace: =========
/lib64/libc.so.6[0x3d5ec75e66]
/lib64/libc.so.6[0x3d5ec762ed]
/lib64/libc.so.6[0x3d5ec79125]
/lib64/libc.so.6(__libc_malloc+0x71)[0x3d5ec7a6b1]
/apps/GCC/4.8.3/lib64/libstdc++.so.6(_Znwm+0x1d)[0x2ac4239f52bd]
/apps/GCC/4.8.3/lib64/libstdc++.so.6(_Znam+0x9)[0x2ac4239f53b9]
/home/mn/ale_0.4.4/ale_0_4/libale.so(_ZN8Settings11setInternalERKSsS1_ib+0x243)[0x2ac422f7acf3]
/home/mn/ale_0.4.4/ale_0_4/libale.so(_ZN8SettingsC1EP7OSystem+0xaa)[0x2ac422f7f48a]
/home/mn/ale_0.4.4/ale_0_4/libale.so(_ZN12SettingsUNIXC1EP7OSystem+0x16)[0x2ac422fab256]
./dqn(_ZN12ALEInterface7loadROMESs+0x164)[0x40a504]
./dqn(main+0x87)[0x40cbe7]
/lib64/libc.so.6(__libc_start_main+0xfd)[0x3d5ec1ed5d]
./dqn[0x406b49]
======= Memory map: ========
00400000-0041d000 r-xp 00000000 00:18 9001770                            /home/mn/caffe-dqn-old/dqn-in-the-caffe-master/dqn
0061d000-0061e000 rw-p 0001d000 00:18 9001770                            /home/mn/caffe-dqn-old/dqn-in-the-caffe-master/dqn
0194c000-019d0000 rw-p 00000000 00:00 0                                  [heap]
3cf8400000-3cf8434000 r-xp 00000000 08:03 32506823                       /usr/lib64/libfontconfig.so.1.4.4
3cf8434000-3cf8634000 ---p 00034000 08:03 32506823                       /usr/lib64/libfontconfig.so.1.4.4
3cf8634000-3cf8636000 rw-p 00034000 08:03 32506823                       /usr/lib64/libfontconfig.so.1.4.4
3cf8800000-3cf8898000 r-xp 00000000 08:03 32513694                       /usr/lib64/libfreetype.so.6.3.22
3cf8898000-3cf8a97000 ---p 00098000 08:03 32513694                       /usr/lib64/libfreetype.so.6.3.22
3cf8a97000-3cf8a9d000 rw-p 00097000 08:03 32513694                       /usr/lib64/libfreetype.so.6.3.22
3cf8c00000-3cf8c2a000 r-xp 00000000 08:03 32510995                       /usr/lib64/libpangoft2-1.0.so.0.2800.1
3cf8c2a000-3cf8e29000 ---p 0002a000 08:03 32510995                       /usr/lib64/libpangoft2-1.0.so.0.2800.1
3cf8e29000-3cf8e2b000 rw-p 00029000 08:03 32510995                       /usr/lib64/libpangoft2-1.0.so.0.2800.1
3cf9000000-3cf900b000 r-xp 00000000 08:03 32507285                       /usr/lib64/libpangocairo-1.0.so.0.2800.1
3cf900b000-3cf920b000 ---p 0000b000 08:03 32507285                       /usr/lib64/libpangocairo-1.0.so.0.2800.1
3cf920b000-3cf920c000 rw-p 0000b000 08:03 32507285                       /usr/lib64/libpangocairo-1.0.so.0.2800.1
3cf9400000-3cf9476000 r-xp 00000000 08:03 32513760                       /usr/lib64/libcairo.so.2.10800.8
3cf9476000-3cf9676000 ---p 00076000 08:03 32513760                       /usr/lib64/libcairo.so.2.10800.8
3cf9676000-3cf9679000 rw-p 00076000 08:03 32513760                       /usr/lib64/libcairo.so.2.10800.8
3cf9800000-3cf9c73000 r-xp 00000000 08:03 32513852                       /usr/lib64/libgtk-x11-2.0.so.0.2400.23
3cf9c73000-3cf9e73000 ---p 00473000 08:03 32513852                       /usr/lib64/libgtk-x11-2.0.so.0.2400.23
3cf9e73000-3cf9e7e000 rw-p 00473000 08:03 32513852                       /usr/lib64/libgtk-x11-2.0.so.0.2400.23
3cf9e7e000-3cf9e80000 rw-p 00000000 00:00 0
3cfa000000-3cfa0bb000 r-xp 00000000 08:03 32507037                       /usr/lib64/libgdk-x11-2.0.so.0.2400.23
3cfa0bb000-3cfa2bb000 ---p 000bb000 08:03 32507037                       /usr/lib64/libgdk-x11-2.0.so.0.2400.23
3cfa2bb000-3cfa2c0000 rw-p 000bb000 08:03 32507037                       /usr/lib64/libgdk-x11-2.0.so.0.2400.23
3d5e800000-3d5e820000 r-xp 00000000 08:03 56623130                       /lib64/ld-2.12.so
3d5ea1f000-3d5ea20000 r--p 0001f000 08:03 56623130                       /lib64/ld-2.12.so
3d5ea20000-3d5ea21000 rw-p 00020000 08:03 56623130                       /lib64/ld-2.12.so
3d5ea21000-3d5ea22000 rw-p 00000000 00:00 0
3d5ec00000-3d5ed8a000 r-xp 00000000 08:03 56623132                       /lib64/libc-2.12.so
3d5ed8a000-3d5ef8a000 ---p 0018a000 08:03 56623132                       /lib64/libc-2.12.so
3d5ef8a000-3d5ef8e000 r--p 0018a000 08:03 56623132                       /lib64/libc-2.12.so
3d5ef8e000-3d5ef8f000 rw-p 0018e000 08:03 56623132                       /lib64/libc-2.12.so
3d5ef8f000-3d5ef94000 rw-p 00000000 00:00 0
3d5f000000-3d5f002000 r-xp 00000000 08:03 56623234                       /lib64/libdl-2.12.so
3d5f002000-3d5f202000 ---p 00002000 08:03 56623234                       /lib64/libdl-2.12.so
3d5f202000-3d5f203000 r--p 00002000 08:03 56623234                       /lib64/libdl-2.12.so
3d5f203000-3d5f204000 rw-p 00003000 08:03 56623234                       /lib64/libdl-2.12.so
3d5f400000-3d5f417000 r-xp 00000000 08:03 56623134                       /lib64/libpthread-2.12.so
3d5f417000-3d5f617000 ---p 00017000 08:03 56623134                       /lib64/libpthread-2.12.so
3d5f617000-3d5f618000 r--p 00017000 08:03 56623134                       /lib64/libpthread-2.12.so
3d5f618000-3d5f619000 rw-p 00018000 08:03 56623134                       /lib64/libpthread-2.12.so
3d5f619000-3d5f61d000 rw-p 00000000 00:00 0
3d5f800000-3d5f883000 r-xp 00000000 08:03 56623460                       /lib64/libm-2.12.so
3d5f883000-3d5fa82000 ---p 00083000 08:03 56623460                       /lib64/libm-2.12.so
3d5fa82000-3d5fa83000 r--p 00082000 08:03 56623460                       /lib64/libm-2.12.so
3d5fa83000-3d5fa84000 rw-p 00083000 08:03 56623460                       /lib64/libm-2.12.so
3d5fc00000-3d5fc07000 r-xp 00000000 08:03 56623467                       /lib64/librt-2.12.so
3d5fc07000-3d5fe06000 ---p 00007000 08:03 56623467                       /lib64/librt-2.12.so
3d5fe06000-3d5fe07000 r--p 00006000 08:03 56623467                       /lib64/librt-2.12.so
3d5fe07000-3d5fe08000 rw-p 00007000 08:03 56623467                       /lib64/librt-2.12.so
3d60000000-3d60015000 r-xp 00000000 08:03 56623474                       /lib64/libz.so.1.2.3
3d60015000-3d60214000 ---p 00015000 08:03 56623474                       /lib64/libz.so.1.2.3
3d60214000-3d60215000 r--p 00014000 08:03 56623474                       /lib64/libz.so.1.2.3
3d60215000-3d60216000 rw-p 00015000 08:03 56623474                       /lib64/libz.so.1.2.3
3d60400000-3d604db000 r-xp 00000000 08:03 32510838                       /usr/lib64/libgstreamer-0.10.so.0.25.0**\* Aborted at 1427614429 (unix time) try "date -d @1427614429" if you are using GNU date ***
PC: @       0x3d5ec32625 (unknown)
**\* SIGABRT (@0x4edd00006d34) received by PID 27956 (TID 0x2ac42df8b9c0) from PID 27956; stack trace: ***
    @       0x3d5ec326a0 (unknown)
    @       0x3d5ec32625 (unknown)
    @       0x3d5ec33e05 (unknown)
    @       0x3d5ec70537 (unknown)
    @       0x3d5ec75e66 (unknown)
    @       0x3d5ec762ed (unknown)
    @       0x3d5ec79125 (unknown)
    @       0x3d5ec7a6b1 (unknown)
    @     0x2ac4239f52bd operator new()
    @     0x2ac4239f53b9 operator new[]()
    @     0x2ac422f7acf3 Settings::setInternal()
    @     0x2ac422f7f48a Settings::Settings()
    @     0x2ac422fab256 SettingsUNIX::SettingsUNIX()
    @           0x40a504 ALEInterface::loadROM()
    @           0x40cbe7 main
    @       0x3d5ec1ed5d (unknown)
    @           0x406b49 (unknown)
Aborted (core dumped)

**Comment by mohammad63** [comment]
any help?

**Comment by muupan** [comment]
It seems the problem is related to building or linking ALE, but I'm not sure. Would you provide more information on how you built ALE and dqn?

**Comment by mohammad63** [comment]
Thank for your response.
The issue was related to having multiple caffe versions.
It has been resolved.
Thanks
